MyApps/Carts/urls.py
from django.urls import path
from . import views

app_name = "Carts"

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name="add"),
    path('eliminar', views.remove, name="remove"),
]

MyApps/Orders/urls.py
from django.urls import path
from . import views

app_name = 'Orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path("establecer/direccion/<int:pk>", views.check_address, name="check_address"),
    path("confirmacion", views.confirm, name="confirm"),
    path("cancelar", views.cancel, name="cancel"),
    path("cancelar_pedido/<orderId>", views.cancel_order_created, name="cancel_order_created"),
    path("creado", views.created, name="created"),
    path("confirmar/<orderId>", views.complete, name="completed"),
    path("mensaje_exito", views.success, name="success"),
    path("mis_pedidos", views.OrderListView.as_view(), name="orders_list"),
    path("mis_pedidos/cancelados", views.orders_cancelled, name="orders_cancelled"),
    path("mis_pedidos/en_proceso", views.orders_unconfirmed, name="orders_unconfirmed"),
    path("pago", views.payment, name="payment"),
    path('generatePDF/<info>', views.orderPdf, name='generatePDF'),
]

core_inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.ProductListView.as_view(), name='index'), # Ruta raiz
    path('main/', include('MyApps.Products.urls')),
    path('carrito/', include('MyApps.Carts.urls')),
    path('pedidos/', include('MyApps.Orders.urls')),
    path('compras/', include('MyApps.Purchases.urls')),
    path('ventas/', include('MyApps.Sales.urls')),
    path('productos/', include('MyApps.Products.urls')),
    path('pagos/', include('MyApps.BillingProfiles.urls')),
    path('codigos/', include('MyApps.PromoCodes.urls')),
    path('perfil/', include('MyApps.Users.urls')),
    path('login', views.login_view, name='login'), # Login
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('contacto', views.contact, name='contact'),
    path('direcciones/', include('MyApps.ShippingAddresses.urls')),
    path('graficos/', include('MyApps.Charts.urls')),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name="Password/forgot_password.html"), name="password_reset"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='Password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(template_name="Password/password_reset_done.html"), name='password_reset_done'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name="Password/password_reset_complete.html"), name='password_reset_complete'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="Password/change_password.html"), name="change_password"),
    path('change-success/', auth_views.PasswordChangeDoneView.as_view(template_name="Password/password_change_done.html"), name="password_change_done"),

]
# 404 redirect
handler404 = views.error_404_view

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

MyApps/Carts/models.py
import uuid
import decimal
from django.db import models
from django.contrib.auth.models import User
from MyApps.Products.models import Product
from MyApps.Orders.common import OrderStatus
from django.db.models.signals import pre_save, m2m_changed, post_save
from django.contrib.auth import get_user_model
User = get_user_model()

class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null = False, blank=False, unique = True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete = models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProducts')
    subtotal = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    
    FEE = 0 # Impuesto
    
    def __str__(self):
        return self.cart_id
    
    class Meta:
        verbose_name = "Carrito"
        verbose_name_plural = "Carritos"
        db_table="carts"

        
    def update_totals(self):
        self.update_subtotal()
        self.update_total()
        
        if self.order:
            self.order.update_total()
        
    def update_subtotal(self):
        self.subtotal = sum([
            cp.quantity * cp.product.price for cp in self.products_related()
        ])
        self.save()

    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()
        
    def products_related(self):
        return self.cartproducts_set.select_related('product')
    
    @property
    def order(self):
        return self.order_set.filter(status=OrderStatus.CREATED).first()

class CartProductsManager(models.Manager):
    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)

        if not created:
            quantity = object.quantity + quantity
        
        total = quantity * product.price
        object.update_quantity(quantity)
        object.set_total(total)
        return object

class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.IntegerField(default = 1)
    total = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    
    objects = CartProductsManager()
    
    def update_quantity(self, quantity =1):
        self.quantity = quantity
        self.save()
        
    def set_total(self, total=0):
        self.total = total
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()
    
def change_product_status(sender, instance,*args, **kwargs):
    if instance.stock <= 0:
        instance.status = 1
    else:
        instance.status = 0

pre_save.connect(set_cart_id, sender=Cart)
pre_save.connect(change_product_status, sender=Product)

post_save.connect(post_save_update_totals, sender = CartProducts)
m2m_changed.connect(update_totals, sender = Cart.products.through)

MyApps/Carts/views.py
from django.shortcuts import render
from . models import Cart
from . utils import create_cart #Aqui se creó el metodo
from MyApps.Products.models import Product
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from . models import CartProducts

def cart(request):
    cart = create_cart(request)
    return render(request, "Carrito/cart.html", {
        "cart": cart
        })
    
def add(request):
    cart = create_cart(request)
    product = get_object_or_404(Product, pk = request.POST.get('product_id'))
    quantity = int(request.POST.get('txtQuantity', 1)) # Por defecto 1    

    # cart.products.add(product, through_defaults={
    #     'quantity':quantity
    # })
    cart_product = CartProducts.objects.create_or_update_quantity(
        cart=cart, 
        product = product, 
        quantity = quantity
    )
    
    new_stock = product.stock - quantity
    product.stock = new_stock
    product.save()

    messages.success(request, "¡{0} productos agregados!".format(quantity))
    
    return render(request, 'Carrito/productDetail.html',{"product": product, "cart":cart})

def remove(request):
    cart = create_cart(request)
    product = get_object_or_404(Product, pk = request.POST.get('product_id'))
    
    #Si se elimina del carrito, el stock se restablece
    p = cart.cartproducts_set.get(product_id = request.POST.get('product_id'))
    product.stock = product.stock + p.quantity
    product.save()

    cart.products.remove(product)
    messages.success(request, "¡Producto eliminado!")
    return redirect('Carts:cart')
    

templates/Carrito/add.html
<form action="{% url 'Carts:add' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id_product }}">
    <div class="d-flex gap-2 my-3">
        <button type="button" id="remove" class="button-detail">-</button>
        <input type="number" id="txtQuantity" value="1" class="text-center formulario__input p-0" name="txtQuantity" readonly>
        <button type="button" id="add" class="button-detail">+</button>
    </div>
    <div class="mt-2">
        {% if product.status != 0 or product.stock == 0 %}
            <button type="submit" class="shadow fw-bold btn btn-warning disabled">Añadir al carrito 🛒</button>
        {% else %}
            <button type="submit" id="btnAddToCar" class="button-detail w-75">Añadir al carrito 🛒</button>
        {% endif %}
    </div>
</form>

<script type="text/javascript">
    const add = document.getElementById("add")
    const remove = document.getElementById("remove")
    const quantity = document.getElementById("txtQuantity")

    add.addEventListener("click", ()=>{
        if (quantity.value < {{product.stock}}) {
            quantity.value= parseInt(quantity.value)+1
        }
    })
    remove.addEventListener("click", ()=>{
        value = parseInt(quantity.value)
        if(value != 1){
            value -= 1
        }
        quantity.value = value
    })
    {% comment %} quantity.addEventListener("keyup", ()=>{
        if (quantity.value < {{product.stock}} && Number(quantity.value) > 0) {
            quantity.value = parseInt(quantity.value)
            btnAddToCar.removeAttribute("disabled")
        }else{
            btnAddToCar.setAttribute("disabled", true)
        }
    }) {% endcomment %}
</script>

templates/Carrito/cart.html
{% extends '../baseIndex.html' %}

{% block title %} Carrito{% endblock %}

{% block content %}
{% if cart.products.exists %}
        <div class="container px-5 py-4 bg-white rounded-3">
            <h1 class="text-center rounded-3 p-0 m-0 pb-4">Mi carrito de compras</h1>
            <div class="row justify-content-between">
                <div class="col-sm-12 col-xl-8">
                    <table class="table table-striped mb-0 table-bordered border-dark text-center">
                        <thead style="background-color: #F37828;">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Precio Unitario</th>
                            <th scope="col">Cantidad</th>
                            <th scope="col">Imagen</th>
                            <th scope="col">Acción</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cp in cart.products_related %}
                        {% with product=cp.product  %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{product.name}}</td>
                                <td>
                                    {% load humanize %}
                                    ${{product.price|intcomma}}
                                </td>
                                <td>{{ cp.quantity }}</td>
                                <td>
                                    {% if product.image_product.url %}
                                        <img src={{product.image_product.url}} alt="{{product.name}}" width="60px" height="60px" class="img-responsive"/>   
                                    {% endif %}
                                </td>
                                <td>
                                    {% include 'Carrito/delete.html' %}
                                </td>
                            </tr>
                        {% endwith %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-sm-12 col-xl-3">
                    <div class="shadow h-100 card border-dark  text-center">
                        <div class="card-header fw-bold" style="background-color: #F37828;">Detalle de compra</div>
                        <div class="card-body">
                            <div class="fw-bold h5 m-0">
                                {% load humanize %}
                                Subtotal ({{ cart.products.count }}): <span class="text-danger">${{ cart.subtotal|intcomma }}</span>
                            </div>
                            <div class="mt-4">
                                <a href="{% url 'Orders:order' %}" class="button-detail" style="margin-top:50px">Proceder al pago</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="container p-5 bg-white rounded-3">
            <h1 class="text-center rounded-3 mb-3">Mi carrito de compras</h1>
            <div class="row justify-content-center align-items-center">
                <div class="col-sm-12 text-center">
                    <h4 class="opacity-75">Tu carrito de compras 🛒 esta vacio</h4>
                    <a href="{% url 'index' %}" class="h5 text-decoration-none opacity-75 text-primary">Ir a comprar🍅</a>
                </div>
            </div>
        </div>
        {% endif %}
{% endblock content %}

templates/Carrito/delete.html
<form method="POST" action="{% url 'Carts:remove' %}">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id_product }}">
    <button type="submit" class="btn btn-danger">Quitar</button>
</form>

templates/Carrito/productDetail.html
{% extends '../baseIndex.html' %}
{% block title %} Detalle{% endblock title %}
{% block content %}
<div class="container d-flex justify-content-center pb-3">
  <div class="card-product text-center">
    <div class="card-head">
      <img
        src="{{product.image_product.url}}"
        alt="{{product.name}} imagen"
        width="200px"
        height="200px"
        class="img-responsive"
      />
    </div>
    <div class="card-body">
      <div class="product-desc">
        <span class="product-title d-flex justify-content-center flex-wrap">
          <strong>{{product.name}}</strong>
          {% if product.status == 0 and product.stock != 0 %}
          <span>({{product.stock}} unidades disponibles)</span>
          {% else %}
          <span class="badge-status bg-danger">Agotado</span>
          {% endif %}
        </span>
        <span class="product-caption"> {{product.descripction}} </span>
      </div>
      <div class="product-properties">
        {% load humanize %}
        <span class="product-price">$ {{product.price|intcomma }} COP</span>
      </div>
      {% include 'Carrito/add.html' %}
    </div>
    <footer>
    </footer>

  </div>
</div>
{% endblock content %}