MyApps/BillingProfiles/urls.py
from django.urls import path
from . import views

app_name="billing"

urlpatterns = [
    path("nuevo", views.create, name="create"),
]

MyApps/Orders/urls.py
from django.urls import path
from . import views

app_name = 'Orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path("establecer/direccion/<int:pk>", views.check_address, name="check_address"),
    path("confirmacion", views.confirm, name="confirm"),
    path("cancelar", views.cancel, name="cancel"),
    path("cancelar_pedido/<orderId>", views.cancel_order_created, name="cancel_order_created"),
    path("creado", views.created, name="created"),
    path("confirmar/<orderId>", views.complete, name="completed"),
    path("mensaje_exito", views.success, name="success"),
    path("mis_pedidos", views.OrderListView.as_view(), name="orders_list"),
    path("mis_pedidos/cancelados", views.orders_cancelled, name="orders_cancelled"),
    path("mis_pedidos/en_proceso", views.orders_unconfirmed, name="orders_unconfirmed"),
    path("pago", views.payment, name="payment"),
    path('generatePDF/<info>', views.orderPdf, name='generatePDF'),
]

MyApps/PromoCodes/urls.py
from django.urls import path
from . import views

app_name="promo_code"

urlpatterns = [
    path("validar",views.validate, name="validate"),
    path("enviar_code",views.send_promo_code, name="send_promo_code"),
    
]

MyApps/ShippingAddresses/urls.py
from django.urls import path
from . import views

app_name='address'

urlpatterns = [
    path('', views.shipping_address, name='shipping_addresses'),
    path('crear/', views.create, name='createAddress'),
    path('editarDireccion/<int:id>', views.address_to_update, name='updateAnAddress'),
    path('editar/', views.update, name='update'),
    path('eliminar/<int:id>', views.delete, name='delete'),
    path("default/<int:pk>", views.default, name="default")
]

core_inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.ProductListView.as_view(), name='index'), # Ruta raiz
    path('main/', include('MyApps.Products.urls')),
    path('carrito/', include('MyApps.Carts.urls')),
    path('pedidos/', include('MyApps.Orders.urls')),
    path('compras/', include('MyApps.Purchases.urls')),
    path('ventas/', include('MyApps.Sales.urls')),
    path('productos/', include('MyApps.Products.urls')),
    path('pagos/', include('MyApps.BillingProfiles.urls')),
    path('codigos/', include('MyApps.PromoCodes.urls')),
    path('perfil/', include('MyApps.Users.urls')),
    path('login', views.login_view, name='login'), # Login
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('contacto', views.contact, name='contact'),
    path('direcciones/', include('MyApps.ShippingAddresses.urls')),
    path('graficos/', include('MyApps.Charts.urls')),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name="Password/forgot_password.html"), name="password_reset"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='Password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(template_name="Password/password_reset_done.html"), name='password_reset_done'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name="Password/password_reset_complete.html"), name='password_reset_complete'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="Password/change_password.html"), name="change_password"),
    path('change-success/', auth_views.PasswordChangeDoneView.as_view(template_name="Password/password_change_done.html"), name="password_change_done"),

]
# 404 redirect
handler404 = views.error_404_view

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

MyApps/Orders/models.py
import uuid
from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth import get_user_model
from MyApps.Carts.models import Cart
from MyApps.PromoCodes.models import PromoCode
from MyApps.ShippingAddresses.models import ShippingAddress
from MyApps.BillingProfiles.models import BillingProfile
from . common import OrderStatus, choices
from django.utils.html import format_html
User = get_user_model()

class Order(models.Model):
    order_id = models.CharField(max_length=100, null = False, blank = False, unique=True, verbose_name="Id")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Cliente")
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length = 50, 
                              choices=choices, 
                              default=OrderStatus.CREATED, verbose_name="Estado")
    shipping_total = models.PositiveIntegerField(default=2000, verbose_name="Envio")
    total = models.PositiveIntegerField(default=0, verbose_name="Total pago")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    shipping_address = models.ForeignKey(ShippingAddress, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Dirección de envio")
    promo_code = models.OneToOneField(PromoCode, null=True, blank=True, on_delete=models.CASCADE, verbose_name="Código de promoción")
    billing_profile = models.ForeignKey(BillingProfile, null=True, blank=True,on_delete=models.CASCADE, verbose_name="Info de pago")
    cancelled_by = models.IntegerField(default=0, verbose_name="Cancelado por")
    
    def __str__(self):
        return self.order_id
    
    class Meta:
        verbose_name = "Pedidos"
        verbose_name_plural = "pedidos"
        db_table="orders"

    
    def apply_promo_code(self, promo_code):
        if self.promo_code is None:
            self.promo_code = promo_code
            self.save()
            self.update_total()
            promo_code.use()
        
    def get_or_set_billing_profile(self):
        if self.billing_profile:
            return self.billing_profile 
        billing_profile = self.user.billing_profile
        
        if billing_profile:
            self.update_billing_profile(billing_profile)

        return billing_profile    
    
    def update_billing_profile(self, billing_profile):
        self.billing_profile = billing_profile
        self.save()
        
    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address
        
        shipping_address = self.user.shippingAddress
        if shipping_address:
            self.update_shipping_address(shipping_address)
            
        return shipping_address
    
    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()
    
    def created(self):
        self.status = OrderStatus.CREATED
        self.save()
        
    def cancel(self, user):
        self.status = OrderStatus.CANCELED
        self.cancelled_by = user.dni 
        self.save()
        
    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()
        
    def cancelled(self):
        self.status = OrderStatus.CANCELED
        self.save()
    
    def update_total(self):
        self.total = self.get_total()
        self.save()
    
    def get_discount(self):
        if self.promo_code:
            return self.promo_code.discount       
        return 0
    
    def get_total(self):
        return self.cart.total + self.shipping_total - self.get_discount()

        
def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())[:5]

def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()


pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

MyApps/Orders/views.py
import threading
import os
from django.shortcuts import render, redirect, get_object_or_404
from MyApps.Carts.utils import create_cart, destroy_cart
from MyApps.Products.models import Product
from MyApps.ShippingAddresses.models import ShippingAddress
from . models import Order
from . utils import get_or_created_order, breadcrumb, destroy_order
from . mails import Mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic.list import ListView
from django.db.models.query import EmptyQuerySet
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders

@login_required(login_url='login')
def orderPdf(request, info):
    order = Order.objects.filter(order_id = info).first()
    template = get_template("ReportesPDF/orderPdf.html")
    
    if request.user.id != order.user.id and not request.user.is_staff:
        messages.error(request, "¡Estas tratando de ingresar a urls no permitidas, por seguridad hemos registrado tus datos y tu dirección IP!")
        return redirect('index')
    
    context = {
        "products": order.cart.products.all(),
        "order": order,
    }
    html = template.render(context)
    response = HttpResponse(content_type="application/pdf")
    response['Content-Disposition'] = f'attachment; filename="pedido ({order.order_id}).pdf"'
    pisa_status = pisa.CreatePDF(
        html, dest=response)
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

class OrderListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name = 'Pedidos/orders_history.html'
    
    def cart(self):
        cart = create_cart(self.request)
        return cart
    
    def orders_cancelled(self):
        return self.request.user.orders_cancelled()
    
    def orders_unconfirmed(self):
        return self.request.user.orders_unconfirmed()
    
    def get_queryset(self):
        return self.request.user.orders_completed()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = self.cart()
        context['orders_cancelled'] = self.orders_cancelled()
        context['orders_unconfirmed'] = self.orders_unconfirmed()
        return context

@login_required(login_url='login')
def orders_cancelled(request):
    cart = create_cart(request)    
    orders_completed = request.user.orders_completed()
    orders_cancelled = request.user.orders_cancelled()
    return render(request, 'Pedidos/orders_cancelled.html', {
        'cart': cart,
        'order': order,
        'orders_cancelled':orders_cancelled,
    })
    
@login_required(login_url='login')
def orders_unconfirmed(request):
    cart = create_cart(request)    
    orders_unconfirmed = request.user.orders_unconfirmed()
    
    return render(request, 'Pedidos/orders_unconfirmed.html', {
        'cart': cart,
        'order': order,
        'orders_unconfirmed':orders_unconfirmed,
    })

@login_required(login_url='login')
def order(request):
    cart = create_cart(request)
    order = get_or_created_order(cart, request)
    return render(request, 'Pedidos/order.html', {
        'cart': cart,
        'order': order,
        'breadcrumb':breadcrumb()
    })

@login_required(login_url='login')
def address(request):
    cart = create_cart(request)
    order = get_or_created_order(cart, request)
    
    print(order)
    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.shippingaddress_set.count() > 1
    
    return render(request, 'Pedidos/address.html',{
        "cart":cart,
        "order": order,
        "shipping_address":shipping_address,
        'breadcrumb':breadcrumb(address=True),
        "can_choose_address":can_choose_address
    })
    
@login_required(login_url='login')
def select_address(request):
    shipping_addresses = request.user.shippingaddress_set.all()
    return render(request, 'Pedidos/select_address.html',{
        'breadcrumb':breadcrumb(address=True),
        'shipping_addresses':shipping_addresses 
    })

@login_required(login_url='login')
def check_address(request, pk):
    cart = create_cart(request)
    order = get_or_created_order(cart, request)
    
    shipping_address = get_object_or_404(ShippingAddress, pk=pk)
    
    if request.user.id != shipping_address.user_id:
        messages.error(request, "¡Estas tratando de ingresar a urls no permitidas, por seguridad hemos registrado tus datos y tu dirección IP!")
        return redirect('index')
    
    order.update_shipping_address(shipping_address)
    messages.success(request, "¡Has cambiado tu direccion de envio!")
    return redirect('Orders:address')

@login_required(login_url='login')
def confirm(request):
    cart = create_cart(request)
    order = get_or_created_order(cart, request)
    
    shipping_address = order.shipping_address
    
    print(shipping_address)
    if shipping_address is None:
        return redirect('Orders:address')
    
    return render(request, 'Pedidos/confirm.html',{
        'cart':cart,
        'order':order,
        'shipping_address': shipping_address,
        'breadcrumb':breadcrumb(address=True, confirmation=True, payment=True),
    })
    

@login_required(login_url='login')
def cancel(request):
    cart = create_cart(request)
    order = get_or_created_order(cart, request)
    
    if request.user.id != order.user_id:
        messages.error(request, "¡Estas tratando de ingresar a urls no permitidas, por seguridad hemos registrado tus datos y tu dirección IP!")
        return redirect('index')
    
    if cart.cartproducts_set.all():
        for p in cart.cartproducts_set.all():
            product = get_object_or_404(Product, pk = p.product_id)
            product.stock = product.stock + p.quantity
            product.save()
            
    order.cancel(request.user)
    destroy_cart(request)
    destroy_order(request)
    messages.error(request, "¡Tu pedido ha sido cancelado!")

    return redirect('index')


@login_required(login_url='login')
def created(request):
    cart = create_cart(request)
    order = get_or_created_order(cart, request)

    if not order.shipping_address:
        destroy_order(request)
        
    if request.user.id != order.user_id:
        messages.error(request, "¡Estas tratando de ingresar a urls no permitidas, por seguridad hemos registrado tus datos y tu dirección IP!")
        return redirect('index')
    
    order.created()
    destroy_cart(request)
    destroy_order(request)
    messages.success(request, "¡Pedido exitoso!")
    return redirect('Orders:success')


@login_required(login_url='login')
def complete(request, orderId):
    order = Order.objects.filter(order_id = orderId).first()
    cart = order.cart

    if request.user.id != order.user_id and not request.user.is_staff:
        messages.error(request, "¡Estas tratando de ingresar a urls no permitidas, por seguridad hemos registrado tus datos y tu dirección IP!")
        return redirect('index')

    order.complete()
    #Envio de correos de forma asincrona
    thread = threading.Thread(target=Mail.send_complete_order, args=(
        order, order.user ,cart
    ))
    thread.start()
    destroy_cart(request)
    destroy_order(request)
    messages.success(request, f"¡Recuerda entregar el pedido # {orderId} en {order.shipping_address.address}!")
        
    return redirect('/admin/Orders/order')

@login_required(login_url='login')
def cancel_order_created(request, orderId):
    order = Order.objects.filter(order_id = orderId).first()
    cart = order.cart
    
    if request.user.id != order.user_id and not request.user.is_staff:
        messages.error(request, "¡Estas tratando de ingresar a urls no permitidas, por seguridad hemos registrado tus datos y tu dirección IP!")
        return redirect('index')
    
    if cart.cartproducts_set.all():
        for p in cart.cartproducts_set.all():
            product = get_object_or_404(Product, pk = p.product_id)
            product.stock = product.stock + p.quantity
            product.save()
 
    order.cancel(request.user)
    destroy_cart(request)
    destroy_order(request)
    
    if request.user.is_staff:
        messages.error(request, f"Has cancelado el pedido # {orderId}")
        return redirect('/admin/Orders/order')
    
    messages.error(request,"Has cancelado tu pedido")
    return redirect('/')


@login_required(login_url='login')
def success(request):
    return render(request, 'Pedidos/success_order.html')

@login_required(login_url='login')
def payment(request):
    cart = create_cart(request)
    order = get_or_created_order(cart, request)
    
    billing_profile = order.get_or_set_billing_profile()
    return render(request, 'Pedidos/payment.html',{
        "cart": cart,
        "order":order,
        "billing_profile":billing_profile,
        "breadcrumb": breadcrumb(address=True,payment=True)
    })
    

templates/Pedidos/address.html
{% extends 'baseIndex.html' %}
{% block title %} Dirección{% endblock%}
{% load static %}
{% block content %}
<div class="container bg-white rounded-3 d-flex justify-content-around align-content-start flex-wrap">  
    <div class="steps col-xl-10 col-sm-12 m-3">
        {% include 'Pedidos/stepByStep.html' %}
    </div>
    <div class="col-xl-12 text-center col-sm-12">
        {% if shipping_address %}
            <div class="h3">Recoge tu pedido 📦 en el punto de entrega:</div>
            <div class="d-flex justify-content-center align-items-center">
                <div class="col-sm-4 my-4">
                    <div class="card text-center shadow" style="border-color: #F37828;">
                    <div class="card-body">
                        <img src="{% static 'img/tachuela.svg' %}" alt="tachuela" width="32" height="32">
                        <h5 class="card-title">{{shipping_address.address}}</h5>
                        <hr>
                        <p><span class="fw-bold">Barrio:</span> {{shipping_address.neighborhood}}</p>
                        <p><span class="fw-bold">Localidad:</span> {{shipping_address.zone}}</p>
                        <p><span class="fw-bold">Datos de referencia:</span> {{shipping_address.reference}}</p>
                        <div class="card-footer">
                            <p class="text-muted">Dirección principal</p>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
            {% if can_choose_address %}
                <div class="h4 text-muted">
                    <a href="{% url 'Orders:select_address' %}" class="h4 text-decoration-none opacity-75 text-primary">Elige otra dirección</a>
                </div>
            {% endif %}
            <div class="d-flex justify-content-center p-3">
                <a href="{% url 'Orders:payment' %}" class="button-detail">Continuar</a>
            </div>
        {% else %}
        <div class="row mb-5 mt-1 justify-content-center align-items-center">
            <div class="d-flex flex-wrap flex-column justify-content-center align-items-center text-center">
                <img src="../static/img/address.png" class="address-image" alt="address image">
                <h4 class="opacity-75">No tienes direcciones registradas.</h4>
                {% url 'Orders:address' as next_url %}
                <a href="{% url 'address:shipping_addresses' %}?next={{next_url}}" class="h5 text-decoration-none opacity-75 text-primary">Agregar una nueva ➕</a>
            </div>
        </div>
        {% endif %}
        </div>
</div>
{% endblock content %}

templates/Pedidos/confirm.html
{% extends 'baseIndex.html' %}
{% block title %} Dirección{% endblock%}
{% load static %}
{% block content %}
<div class="container bg-white rounded-3 d-flex justify-content-around align-content-start flex-wrap">  
    <div class="steps col-xl-10 col-sm-12 m-3">
        {% include 'Pedidos/stepByStep.html' %}
    </div>
    <div class="col-xl-11 col-sm-12 p-3">
        
        <div class="card border-dark shadow">
            <div class="card-header h4" style="background-color: #F37828;">
                <div class="fw-bold text-center">Confirma tu pedido</div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-xl-4 border-end">
                        <h6 class="fw-bold">Dirección de envio</h6>
                        <div class="card-text">
                            {{ shipping_address.address }}
                        </div>
                        <div class="card-text">
                            {{ shipping_address.neighborhood }}
                        </div>
                        <div class="card-text">
                            {{ shipping_address.zone }}
                        </div>
                    </div>
                    <div class="col-xl-4  border-end">
                        <h6 class="fw-bold">Método de pago</h6>
                        {% if order.billing_profile %}
                        <div class="card-text">
                            Tarjeta con número *****{{order.billing_profile.last4}}
                        </div>
                        {% else %}
                        <div class="card-text">
                            En efectivo
                        </div>
                        {% endif %}
                    </div>
                    <div class="col-xl-4">
                        <h6 class="fw-bold">Código de descuento</h6>
                        <form class="d-flex" id="promoCodeForm" action="{% url 'promo_code:validate' %}">
                            <input type="text" style="border-radius:20px 0px 0px 20px" id="code" name="code" value="{{order.promo_code.code}}" class="formulario__input" placeholder="Ej: AAD576" {% if order.promo_code %}readonly disabled{% endif %}>
                            <button type="submit" class="btn btn-success" style="border-radius:0px 20px 20px 0px">
                                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="icon icon-tabler icon-tabler-search" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z"/><circle cx="10" cy="10" r="7"/><path d="m21 21-6-6"/></svg>
                            </button>
                        </form>
                        <div class="fw-bold fst-italic text-success" id="promoCodeSuccess">
                            {% if order.promo_code %}
                                ¡Código aplicado!
                            {% endif %}
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-sm-12 p-3">
        <div class="card">
            {% include 'Pedidos/orderProducts.html' %}
        </div>
    </div>
    <div class="col-xl-6 col-sm-12 p-3 d-flex justify-content-end flex-wrap align-content-between">
        <div class="card col-12">
            {% include 'Pedidos/orderResume.html'%}
        </div>
        <div class="fw-bold h5 pt-4">
            <a href="{% url 'Orders:cancel' %}" class="btn btn-danger fw-bold m-0 p-2">Cancelar pedido</a>
            <a href="{% url 'Orders:created' %}" class="btn fw-bold m-0 p-2 text-white" style="background-color:#F37828">Confirmar pedido</a>
        </div>
    </div>
</div>
{% endblock content %}


{% block js %}
    <script>
        const form = document.getElementById("promoCodeForm")
        form.addEventListener('submit', (e)=>{
            e.preventDefault();
            const input = document.getElementById("code");
            const code = input.value;
            const url = form.action + "?code=" + code
            const total = document.getElementById("orderTotal")
            const txtSuccess = document.getElementById("promoCodeSuccess")
            const orderDiscount = document.getElementById("orderDiscount")
            fetch(url)
                .then(res=>res.json())
                .then(data=> {
                    if(data.status){
                        total.innerHTML = `Total a pagar: $${data.total}`
                        orderDiscount.innerHTML = `Descuento: $${data.discount}`
                        txtSuccess.classList.remove('text-danger');
                        txtSuccess.classList.add('text-success');
                        txtSuccess.innerHTML = '¡Código aplicado!';
                        input.setAttribute('disabled', '');
                    }else{
                        txtSuccess.innerHTML = '¡Uups... código no valido!';
                        txtSuccess.classList.remove('text-success');
                        txtSuccess.classList.add('text-danger');
                    }
                })
        })
    </script>
{% endblock %}

templates/Pedidos/order.html
{% extends 'baseIndex.html' %}
{% block title %} Pedido{% endblock%}
{% load static %}
{% block content %}
<div class="container bg-white rounded-3 d-flex justify-content-around align-content-start flex-wrap pb-5">  
    <div class="steps col-xl-10 col-sm-12 m-2">
        {% include 'Pedidos/stepByStep.html' %}
    </div>
    <div class="col-xl-4 col-sm-12">
        {% include 'Pedidos/orderProducts.html' %}
    </div> 
    <div class="col-xl-5 col-sm-12">
        {% include 'Pedidos/orderResume.html' with btnContinue=True %}
    </div>
</div>
{% endblock content %}

templates/Pedidos/orders_history.html
{% extends 'baseIndex.html' %}
{% block title %} Mis pedidos{% endblock%}
{% load static %}
{% block content %}
<div class="container p-4 bg-white rounded-3">  
    <h1 class="text-center mb-4">Mis pedidos📦</h1>
    <div class="d-flex justify-content-end mb-3">
        <a href="{% url 'Orders:orders_list' %}" class="btn btn-success fw-bold mx-1">Realizados</a>
        <a href="{% url 'Orders:orders_cancelled' %}" class="btn btn-danger fw-bold mx-1">Cancelados</a>
        <a href="{% url 'Orders:orders_unconfirmed' %}" class="btn btn-warning fw-bold mx-1">Por confirmar</a>
    </div>

    
    {% if object_list.exists %}
        {% for order in object_list %}
        <div class="card mb-3 border-dark">
            <div class="card-header border-bottom">
                <div class="row">
                    <div class="col-xl-4 col-sm-12">
                        <h6 class="fw-bold">Pedido Realizado</h6>
                        <a data-bs-toggle="collapse" {% if object_list.count > 1 %} href="#aa{{order.order_id}}" {% else %} href="#unique" {% endif %} role="button" aria-expanded="false" aria-controls="collapseExample">
                            {{order.created_at}}
                        </a>
                    </div>
                    <div class="col-xl-4 col-sm-12">
                        <h6 class="fw-bold">Total + envio {% if order.promo_code_id != null %} + descuento {% endif %}</h6>
                        {% load humanize %}
                        <p class="">${{order.total|intcomma}}</p> 
                    </div>
                    <div class="col-xl-4 col-sm-12">
                        <div class="row d-flex align-items-center">
                            <div class="col-6">
                                <h6 class="fw-bold">Enviado a:</h6>
                                <p class="">{{order.shipping_address}}</p>
                            </div>
                            <div class="col-6">
                                <h1 class="text-center">
                                    ✅
                                    <a href="{% url 'Orders:generatePDF' order.order_id %}"><img src="https://icons.veryicon.com/png/o/file-type/file-type-1/pdf-icon.png" alt="pdf" width="40px" height="40px" class="img-responsive mb-2"/></a>
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="collapse" {% if object_list.count > 1 %} id="aa{{order.order_id}}" {% else %} id="unique" {% endif %}>
                <div class="card-body">
                    {% for cp in order.cart.products_related  %}
                    {% with product=cp.product%}
                    <div class="row">
                        <div class="col-xl-4 col-sm-12">
                            {% if product.image_product.url %}
                                <img src={{product.image_product.url}} alt="{{product.name}}" width="60px" height="60px" class="img-responsive"/>   
                            {% endif %}
                        </div>
                        <div class="col-xl-4 col-sm-12">
                            <h6 class="">{{product.name}}</h6>
                            {% load humanize %}
                            <p class="text-danger">${{product.price|intcomma}}</p> 
                        </div>
                        <div class="col-xl-4 col-sm-12">
                            <h6>Cantidad</h6>
                            <h6 class="">{{cp.quantity}}</h6>
                        </div>
                    </div>
                    {% endwith %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endfor %}
    {% elif orders_cancelled.exists %}
        {% block cancelados %}{% endblock %}
    {% elif orders_unconfirmed.exists  %}
        {% block unconfirmed %}{% endblock %}
    {% else %}
        <div class="row h-75 justify-content-center align-items-center">
            <div class="col-sm-12 text-center">
                <h4 class="opacity-75">No tienes pedidos hasta el momento :(</h4>
            </div>
        </div>
    {% endif %}
</div>

  
{% endblock content %}

templates/Pedidos/payment.html
{% extends 'baseIndex.html' %}
{% block title %} Pago{% endblock%}
{% block content %}
<div class="container bg-white rounded-3 d-flex justify-content-around align-content-start flex-wrap">  
    <div class="steps col-xl-10 col-sm-12 m-3">
        {% include 'Pedidos/stepByStep.html' %}
    </div>
    
    <div class="col-xl-8 col-sm-12 pb-5">
        {% if billing_profile %}
        <div class="h3 text-center">Método de pago</div>
            <div class="card mt-2 border-dark">
                <div class="card-body">
                    <div class="card-title">{{billing_profile.brand}}</div>
                    <div class="card-subtitle">****{{billing_profile.last4}}</div>
                </div>
            </div>
        </div>
        {% else %}
            <div class="col-12 text-center">
                <h4 class="opacity-75">No tienes tarjetas de pago registradas.</h4>

                <a href="{% url 'billing:create' %}" class="h5 text-decoration-none opacity-75 text-primary">Agregar una nueva ➕</a>
            </div>
        {% endif %}
        <div class="col-xl-12 col-sm-12 d-flex justify-content-center p-3">
            <a href="{% url 'Orders:confirm' %}" class="button-detail">Continuar</a>
        </div>
    </div>
    
</div>
{% endblock content %}