MyApps/Users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'Users'

urlpatterns = [
    path("informacion/", views.user_info, name="user_info"),
    path("actualizar-informaciom/", views.update_personal_information, name="update_personal_information"),
]

core_inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.ProductListView.as_view(), name='index'), # Ruta raiz
    path('main/', include('MyApps.Products.urls')),
    path('carrito/', include('MyApps.Carts.urls')),
    path('pedidos/', include('MyApps.Orders.urls')),
    path('compras/', include('MyApps.Purchases.urls')),
    path('ventas/', include('MyApps.Sales.urls')),
    path('productos/', include('MyApps.Products.urls')),
    path('pagos/', include('MyApps.BillingProfiles.urls')),
    path('codigos/', include('MyApps.PromoCodes.urls')),
    path('perfil/', include('MyApps.Users.urls')),
    path('login', views.login_view, name='login'), # Login
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('contacto', views.contact, name='contact'),
    path('direcciones/', include('MyApps.ShippingAddresses.urls')),
    path('graficos/', include('MyApps.Charts.urls')),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name="Password/forgot_password.html"), name="password_reset"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='Password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(template_name="Password/password_reset_done.html"), name='password_reset_done'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name="Password/password_reset_complete.html"), name='password_reset_complete'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="Password/change_password.html"), name="change_password"),
    path('change-success/', auth_views.PasswordChangeDoneView.as_view(template_name="Password/password_change_done.html"), name="password_change_done"),

]
# 404 redirect
handler404 = views.error_404_view

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/Perfil/info_user.html
{% extends 'baseIndex.html' %}
{% block title %} Perfil{% endblock%}

{% block css %}
<style>
    .user-card-color{
        background: #F37828;
        background: linear-gradient(135deg, #F37828 8%, #c82930 83%);
        border-radius: 25px;
        color: #fff;
        transition: box-shadow .2s, transform
    }
    .user-card-color:hover{
        box-shadow: 0px 0px 20px rgba(0,0,0,1)
    }
</style>
{% endblock css %}

{% block content %}
<div class="container p-3 d-flex justify-content-center">
    <div class="text-center p-4 user-card-color" id="card">
        <img src="https://cdn-icons-png.flaticon.com/512/4646/4646084.png" alt="user image" width="200px" height="200px"/>   
        <h3 class="first_name">{{request.user.first_name}}<a href="#" id="editName">🖊️</a></h3>
        <form class="form_name d-none pt-2" method="POST" action="{% url 'Users:update_personal_information' %}">
            {% csrf_token %}
            <input type="text" name="new_name" id="new_name" class="form-control text-center formulario__input" value="{{request.user.first_name}}" required/>
            <button type="submit" id="btnSaveName" style="border:none; outline:none">🖊️</button>
        </form>
        <h3 class="last_name">{{request.user.last_name}}<a href="#" id="editLastName">🖊️</a></h3>
        <form class="form_last_name d-none pt-2" method="POST" action="{% url 'Users:update_personal_information' %}">
            {% csrf_token %}
            <input type="text" name="new_last_name" id="new_last_name" class="form-control text-center formulario__input" value="{{request.user.last_name}}" required/>
            <button type="submit" id="btnSaveLastName" style="border:none; outline:none">🖊️</button>
        </form>
        <hr>
            <p><span class="fw-bold">Identificación:</span> {{request.user.dni}}</p>     
            <p><span class="fw-bold">Correo electrónico:</span> {{request.user.email}}</p>
            <p><span class="fw-bold">Registrado el:</span> {{request.user.date_joined.date}}</p>
        <hr>
        <a href="{% url 'change_password' %}" class="text-white">Cambiar contraseña</a>
    </div>
</div>
{% endblock  %}
{% block js %}
    <script>
        const firstName = document.querySelector(".first_name")
        const formName = document.querySelector(".form_name")
        const btnEditName = document.getElementById("editName")
        const lastName = document.querySelector(".last_name")
        const formLastName = document.querySelector(".form_last_name")
        const btnEditLastName = document.getElementById("editLastName")

        const inputNewName = document.getElementById("new_name")
        const inputNewLastName = document.getElementById("new_last_name")
        const btnSaveName = document.getElementById("btnSaveName")
        const btnSaveLastName = document.getElementById("btnSaveLastName")

        btnEditName.addEventListener('click',()=>{
            firstName.classList.add("d-none");
            formName.classList.remove("d-none")
            formName.classList.add("d-flex")
        })
        btnEditLastName.addEventListener('click',()=>{
            lastName.classList.add("d-none");
            formLastName.classList.remove("d-none")
            formLastName.classList.add("d-flex")
        })

        btnSaveName.addEventListener("click",(e)=>{
            if (!isNaN(inputNewName.value) || !isNaN(inputNewLastName.value)){
                e.preventDefault();
                formName.innerHTML+='<p class="fw-bold text-danger">No puedes usar números*</p>'
            }
        })
        btnSaveLastName.addEventListener("click",(e)=>{
            if (!isNaN(inputNewLastName.value)){
                e.preventDefault();
                formLastName.innerHTML+='<p class="fw-bold text-danger">No puedes usar números*</p>'
            }
        })

        const el = document.getElementById("card");
        const { clientWidth, clientHeight } = el;
        el.addEventListener("mouseover", (event) => {
            const { layerX, layerY } = event
            const yRotation = ((layerX - clientWidth / 2) / clientWidth ) * 5
            const xRotation = ((layerY - clientHeight / 2) / clientHeight ) * 5
            const string = `
                perspective(500px)
                scale(1.1)
                rotateX(${xRotation}deg)
                rotateY(${yRotation}deg)`
            el.style.transform = string
        })

        el.addEventListener("mouseout", ()=>{
            el.style.transform = `
            perspective(500px)
            scale(1)
            rotateX(0deg)
            rotateY(0deg)`
        })
    </script>
{% endblock js %}