MyApps/ShippingAddresses/urls.py
from django.urls import path
from . import views

app_name='address'

urlpatterns = [
    path('', views.shipping_address, name='shipping_addresses'),
    path('crear/', views.create, name='createAddress'),
    path('editarDireccion/<int:id>', views.address_to_update, name='updateAnAddress'),
    path('editar/', views.update, name='update'),
    path('eliminar/<int:id>', views.delete, name='delete'),
    path("default/<int:pk>", views.default, name="default")
]

core_inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.ProductListView.as_view(), name='index'), # Ruta raiz
    path('main/', include('MyApps.Products.urls')),
    path('carrito/', include('MyApps.Carts.urls')),
    path('pedidos/', include('MyApps.Orders.urls')),
    path('compras/', include('MyApps.Purchases.urls')),
    path('ventas/', include('MyApps.Sales.urls')),
    path('productos/', include('MyApps.Products.urls')),
    path('pagos/', include('MyApps.BillingProfiles.urls')),
    path('codigos/', include('MyApps.PromoCodes.urls')),
    path('perfil/', include('MyApps.Users.urls')),
    path('login', views.login_view, name='login'), # Login
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('contacto', views.contact, name='contact'),
    path('direcciones/', include('MyApps.ShippingAddresses.urls')),
    path('graficos/', include('MyApps.Charts.urls')),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name="Password/forgot_password.html"), name="password_reset"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='Password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(template_name="Password/password_reset_done.html"), name='password_reset_done'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name="Password/password_reset_complete.html"), name='password_reset_complete'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="Password/change_password.html"), name="change_password"),
    path('change-success/', auth_views.PasswordChangeDoneView.as_view(template_name="Password/password_change_done.html"), name="password_change_done"),

]
# 404 redirect
handler404 = views.error_404_view

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/Direcciones/create.html
<div class="modal fade" id="createAddress" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Dirección</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form class="row g-3" method="POST" id="createAddressForm" action="{% url 'address:createAddress' %}">{% csrf_token %}
                <div class="col-md-12">
                    <label for="address" class="formulario__label">Dirección<span class="asterisco">*</span></label>
                    <input type="text" name="address" id="address" class="form-control validacion-correcta formulario__input"  placeholder="Ej: Calle 32 sur # 14 bis este" required/>
                  </div>
                <div class="col-md-12">
                    <label for="neighborhood" class="formulario__label">Barrio<span class="asterisco">*</span></label>
                    <input type="text" name="neighborhood" id="neighborhood" class="form-control validacion-correcta formulario__input"  placeholder="Ej: Los jardines" required/>
                </div>
                <div class="col-md-12">
                    <label for="zone" class="formulario__label">Localidad<span class="asterisco">*</span></label>
                    <input type="text" name="zone" id="zone" class="form-control validacion-correcta formulario__input"  placeholder="Ej: Suba" required/>
                </div>
                <div class="col-12">
                    <label for="reference" class="formulario__label">Referencia<span class="asterisco">*</span></label>
                    <textarea class="form-control formulario__input_textarea" name="reference" id="reference" rows="2" placeholder="Ej: Puerta amarilla; frente al parque"></textarea>
                </div>
                <span id="msj-validation" class="fw-bold text-danger text-center d-none">*Todos los campos son obligatorios</span>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary" id="btnGuardarAddress">Guardar</button>
                  </div>
              </form>

        </div> 
      </div>
    </div>
</div>

{% block js %}
  <script type="text/javascript">
    const address = document.getElementById("address");
    const neighborhood = document.getElementById("neighborhood");
    const zone = document.getElementById("zone");
    const reference = document.getElementById("reference");
    const save = document.getElementById("btnGuardarAddress");
    const validation = document.getElementById("msj-validation");

    save.addEventListener("click", (e)=>{
      if(!address.value.trim() ||
         !neighborhood.value.trim() ||
         !zone.value.trim() ||
         !reference.value.trim()
      ){
        validation.classList.remove("d-none")
        validation.classList.add("d-block")
        e.preventDefault()
      }
    })

  </script>
{% endblock js %}

templates/Direcciones/delete.html
{% extends 'baseIndex.html' %}
{% block content %}
<script>

</script>
{% endblock content %}

templates/Direcciones/edit.html
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Dirección</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <form class="row g-3" method="POST" id="editAddressForm" action="{% url 'address:update'%}">{% csrf_token %}
              <input type="hidden" name="id" value="{{ shipping_address.id }}">
              <div class="col-md-12">
                  <label for="address" class="formulario__label">Dirección<span class="asterisco">*</span></label>
                  <input type="text" name="address" id="address" value="{{ shipping_address.address }}" class="form-control validacion-correcta formulario__input"  placeholder="Ej: Calle 32 sur # 14 bis este" required/>
              </div>
              <div class="col-md-12">
                  <label for="neighborhood" class="formulario__label">Barrio<span class="asterisco">*</span></label>
                  <input type="text" name="neighborhood" id="neighborhood" value="{{ shipping_address.neighborhood }}" class="form-control validacion-correcta formulario__input"  placeholder="Ej: Los jardines" required/>
              </div>
              <div class="col-md-12">
                  <label for="zone" class="formulario__label">Localidad<span class="asterisco">*</span></label>
                  <input type="text" name="zone" id="zone" value="{{ shipping_address.zone }}" class="form-control validacion-correcta formulario__input"  placeholder="Ej: Suba" required/>
              </div>
              <div class="col-12">
                  <label for="reference" class="formulario__label">Referencia<span class="asterisco">*</span></label>
                  <textarea class="form-control formulario__input_textarea" name="reference" id="reference" rows="2" placeholder="Ej: Puerta amarilla; frente al parque">{{ shipping_address.reference }}</textarea>
              </div>

              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                  <button type="submit" class="btn btn-primary" id="btnGuardar">Confirmar</button>
                </div>
            </form>
      </div> 
    </div>
  </div>

templates/Direcciones/shipping_addresses.html
{% extends 'baseIndex.html' %}
{% block title %} Dirección{% endblock%}
{% load static %}


{% block content %}
<div class="container bg-white rounded-3 p-3">
    <h1 class="text-center rounded-3 mb-3">Mis direcciones 🏠</h1>
    {% if object_list %}
    <a href="#" class="btn text-white fw-bold mb-2" style="background-color: #F37828;" data-bs-toggle="modal" data-bs-target="#createAddress">Agregar</a>
        <div class="row">
            {% for shipping_address in object_list %}
            {% if shipping_address.default %}
                <div class="col-sm-4 mb-4">
                    <div class="card text-center shadow" style="border-color: #F37828;">
                    <div class="card-body">
                        <img src="{% static 'img/tachuela.svg' %}" alt="tachuela" width="32" height="32">
                        <h5 class="card-title">{{shipping_address.address}}</h5>
                        <hr>
                        <p><span class="fw-bold">Barrio:</span> {{shipping_address.neighborhood}}</p>
                        <p><span class="fw-bold">Localidad:</span> {{shipping_address.zone}}</p>
                        <p><span class="fw-bold">Datos de referencia:</span> {{shipping_address.reference}}</p>
                        <div class="card-footer text-right">
                            <a onclick="openModal('editarDireccion/{{shipping_address.pk}}')" class="btn btn-primary fw-bold px-4 py-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" class="icon icon-tabler icon-tabler-edit" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z"/><path d="M9 7H6a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2v-3"/><path d="M9 15h3l8.5-8.5a1.5 1.5 0 0 0-3-3L9 12v3M16 5l3 3"/></svg>
                            </a>
                        </div>
                    </div>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-4 mb-4">
                    <div class="card text-center" style="border-color: #F37828;">
                    <div class="card-body">
                        <h5 class="card-title">{{shipping_address.address}}</h5>
                        <hr>
                        <p class=""><span class="fw-bold">Barrio:</span> {{shipping_address.neighborhood}}</p>
                        <p class=""><span class="fw-bold">Localidad:</span> {{shipping_address.zone}}</p>
                        <p class=""><span class="fw-bold">Datos de referencia:</span> {{shipping_address.reference}}</p>
                        <div class="card-footer text-right">
                            <a onclick="openModal('editarDireccion/{{shipping_address.pk}}')" class="btn btn-primary fw-bold">
                                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" class="icon icon-tabler icon-tabler-edit" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z"/><path d="M9 7H6a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2v-3"/><path d="M9 15h3l8.5-8.5a1.5 1.5 0 0 0-3-3L9 12v3M16 5l3 3"/></svg>
                            </a>
                            <a onclick="modalDelete('eliminar/{{shipping_address.pk}}')" class="btn btn-danger fw-bold">
                                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" class="icon icon-tabler icon-tabler-trash" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z"/><path d="M4 7h16M10 11v6M14 11v6M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-12M9 7V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3"/></svg>
                            </a>
                            <a href="{% url 'address:default' shipping_address.pk %}" class="btn btn-warning fw-bold">Principal</a>
                        </div>
                    </div>
                    </div>
                </div>
            {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <div class="row h-75 justify-content-center align-items-center">
            <div class="col-12 text-center">
                <h4 class="opacity-75">No tienes direcciones registradas.</h4>
                <a href="" class="h5 text-decoration-none opacity-75 text-primary" data-bs-toggle="modal" data-bs-target="#createAddress">Agregar una nueva ➕</a>
            </div>
        </div>
    {% endif %}
</div>
<div class="modal fade" id="editAddress" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>
<script>
    const openModal = (url)=>{
        $("#editAddress").load(url, function(){
            $(this).modal("show");
        });
    }
    const modalDelete = (url) =>{
        Swal.fire({
            title: '¿Estas seguro?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: '¡Si, seguro!',
            cancelButtonText: 'Cancelar'
          }).then((result) => {
            if (result.isConfirmed) {
              location.href = url;
            }
          })
    }
</script>
{% include 'Direcciones/create.html' %}
{% endblock content %}

{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock js %}